import React, { useEffect, useState } from "react";
import Head from "next/head";
import Navbar from "../../components/navbar/Navbar";
import { getAuthentication, fetchGetTable } from "../../AllFetchApi";
import { useRouter } from "next/router";
import GridAllTables from "../../components/tables/GridAllTables";
import FormAddTable from "../../components/form/FormAddTable";
import IconBack from "../../components/icons/IconBack";

export default function restaurant() {
  const [reload, setReload] = useState(false);

  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    getAuthentication()
      .then((resp) => {
        console.log("usuario Autenticato");
      })
      .catch((e) => {
        console.log(e);
        router.push("/");
      });
  }, [id, reload]);
  return (
    <div className="sfondo">
      <Head>
        <title>TControl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icono-app.ico" />
      </Head>
      <Navbar />
      <div
        onClick={() => router.back()}
        className="absolute p-2 rounded-md top-2 left-2 hover:bg-green-300 md:mr-10"
      >
        <IconBack />
      </div>

      <FormAddTable id={id} reload={reload} setReload={setReload} />
      <GridAllTables id={id} reload={reload} setReload={setReload} />
    </div>
  );
}
