import Head from "next/head";
import Form from "../components/Form";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Poggetto finale S2I</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icono-app.ico" />
      </Head>

      <Layout>
        <Form />
      </Layout>
    </div>
  );
}
